import re
from typing import List, Dict, Any

def export_bind_zone(zone_name: str, records: List[Any]) -> str:
    """
    Generates an RFC 1035 compliant BIND zone file string.
    """
    clean_domain = zone_name.rstrip('.')
    lines = [
        f"; BIND Zone File for {clean_domain}",
        f"; Generated by AWS Route 53 Clone",
        f"$ORIGIN {clean_domain}.",
        f"$TTL 300",
        "",
    ]

    for rec in records:
        rec_name = str(getattr(rec, 'name', '') or '')
        rec_type = str(getattr(rec, 'type', 'A') or 'A')
        rec_ttl = getattr(rec, 'ttl', 300) or 300
        rec_val = str(getattr(rec, 'value', '') or '')
        rec_prio = getattr(rec, 'priority', None)

        # Format record prefix relative to $ORIGIN
        if rec_name == clean_domain or rec_name == f"{clean_domain}.":
            rel_name = "@"
        elif rec_name.endswith(f".{clean_domain}"):
            rel_name = rec_name[:-len(f".{clean_domain}")]
        else:
            rel_name = rec_name

        # Format BIND line per record type
        if rec_type == 'MX' and rec_prio is not None:
            formatted_val = f"{rec_prio} {rec_val}"
        elif rec_type == 'TXT' and not rec_val.startswith('"'):
            formatted_val = f'"{rec_val}"'
        else:
            formatted_val = rec_val

        lines.append(f"{rel_name:<20} {rec_ttl:<6} IN  {rec_type:<6} {formatted_val}")

    return "\n".join(lines) + "\n"


def parse_bind_zone(bind_text: str, default_domain: str) -> List[Dict[str, Any]]:
    """
    Parses a basic BIND zone file text into a list of DNS record dicts.
    """
    clean_domain = default_domain.rstrip('.')
    origin = clean_domain
    ttl = 300
    records = []

    lines = bind_text.splitlines()

    for raw_line in lines:
        # Strip comments
        line = raw_line.split(';')[0].strip()
        if not line:
            continue

        # Check directives
        if line.startswith('$ORIGIN'):
            parts = line.split()
            if len(parts) > 1:
                origin = parts[1].rstrip('.')
            continue

        if line.startswith('$TTL'):
            parts = line.split()
            if len(parts) > 1 and parts[1].isdigit():
                ttl = int(parts[1])
            continue

        # Parse record line
        tokens = line.split()
        if len(tokens) < 3:
            continue

        # Check if line starts with name or whitespace (inherits previous name)
        idx = 0
        name_token = tokens[idx]

        if name_token == '@':
            rec_name = origin
            idx += 1
        elif name_token.endswith('.'):
            rec_name = name_token.rstrip('.')
            idx += 1
        elif '.' not in name_token and not name_token.isdigit() and name_token not in ('IN', 'CS', 'CH', 'HS'):
            rec_name = f"{name_token}.{origin}"
            idx += 1
        else:
            rec_name = origin

        # Skip TTL if present
        rec_ttl = ttl
        if idx < len(tokens) and tokens[idx].isdigit():
            rec_ttl = int(tokens[idx])
            idx += 1

        # Skip class if present (e.g. IN)
        if idx < len(tokens) and tokens[idx].upper() in ('IN', 'CS', 'CH', 'HS'):
            idx += 1

        if idx >= len(tokens):
            continue

        rec_type = tokens[idx].upper()
        idx += 1

        if idx >= len(tokens):
            continue

        # Remaining tokens are the record value
        remaining_val = " ".join(tokens[idx:])

        # Parse MX priority if present
        priority = None
        val = remaining_val

        if rec_type == 'MX':
            mx_parts = remaining_val.split(maxsplit=1)
            if len(mx_parts) == 2 and mx_parts[0].isdigit():
                priority = int(mx_parts[0])
                val = mx_parts[1]

        # Filter supported record types
        if rec_type in ('A', 'AAAA', 'CNAME', 'TXT', 'MX', 'NS', 'PTR', 'SRV', 'CAA'):
            records.append({
                'name': rec_name,
                'type': rec_type,
                'ttl': rec_ttl,
                'value': val.strip('"'),
                'priority': priority,
                'routing_policy': 'Simple',
            })

    return records
